resources:
  requests:
    cpu:
      min: 50m
      max: 1
    memory:
      min: 100M
      max: 3G
  limits:
    cpu:
      min: 150m
      max: 2
    memory:
      min: 150M
      max: 4G
healthChecks:
  readiness:
    require: true
  liveness:
    require: true
images:
  tagRequired: true
  whitelistRepos:
    - gcr.io
