resources:
  cpuRequestsMissing: error
  cpuLimitsMissing: error
  memoryRequestsMissing: error
  memoryLimitsMissing: error
images:
  tagNotSpecified: error
healthChecks:
  readinessProbeMissing: warning
  livenessProbeMissing: warning
networking:
  hostAliasSet: error
  hostIPCSet: error
  hostNetworkSet: error
  hostPIDSet: error
  hostPortSet: error
security:
  runAsRootAllowed: warning
  runAsPrivileged: error
  notReadOnlyRootFileSystem: warning
  privilegeEscalationAllowed: error
  capabilities:
    error:
      ifAnyAdded:
        - SYS_ADMIN
        - NET_ADMIN
        - ALL
    warning:
      ifAnyAddedBeyond:
        - CHOWN
        - DAC_OVERRIDE
        - FSETID
        - FOWNER
        - MKNOD
        - NET_RAW
        - SETGID
        - SETUID
        - SETFCAP
        - SETPCAP
        - NET_BIND_SERVICE
        - SYS_CHROOT
        - KILL
        - AUDIT_WRITE
