---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: '{{ template "fullname" . }}'
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}'
  namespace: '{{.Release.Namespace}}'
type: opaque
data:
