{{- if .Values.dashboard.service -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}-dashboard'
  namespace: '{{.Release.Namespace}}'
spec:
  ports:
  - name: dashboard
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: '{{.Release.Name}}'
  type: '{{.Values.dashboard.service.type}}'
{{- end -}}
