apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}'
  namespace: '{{.Release.Namespace}}'
