{{- if .Values.config -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: '{{ template "fullname" . }}'
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}'
  namespace: '{{.Release.Namespace}}'
data:
  config.yml: {{- toYaml .Values.config | indent 2 -}}
{{ end }}
