{{- if .Values.webhook.enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polaris.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
type: Opaque
data:
{{- end -}}
