---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fairwinds-config
data:
  config.yml: |
    resources:
      cpu:
        min: 100m
        max: 500m
      memory:
        min: 100M
        max: 200M
---
apiVersion: v1
kind: Namespace
metadata:
  name: fairwinds
  labels:
    app: fairwinds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fairwinds
  namespace: fairwinds
  labels:
    app: fairwinds
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fairwinds
  labels:
    app: fairwinds
rules:
  - apiGroups:
      - ''
      - 'apps/v1'
      - 'admissionregistration.k8s.io'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fairwinds
  labels:
    app: fairwinds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fairwinds
subjects:
  - kind: ServiceAccount
    name: fairwinds
    namespace: fairwinds
---
apiVersion: v1
kind: Secret
metadata:
  name: fairwinds
  namespace: fairwinds
  labels:
    app: fairwinds
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fairwinds
  namespace: fairwinds
  labels:
    app: fairwinds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fairwinds
  template:
    metadata:
      labels:
        app: fairwinds
    spec:
      serviceAccountName: fairwinds
      containers:
      - name: fairwinds
        image: quay.io/jessgreb/fairwinds
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: certs
          mountPath: /tmp/cert/
        - name: config-yml
          mountPath: /opt/app/config.yml
          subPath: config.yml
          readOnly: true
      volumes:
      - name: config-yml
        configMap:
          name: fairwinds-config
      - name: certs
        secret:
          secretName: fairwinds
